# Generated by Django 2.2.4 on 2019-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='post',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
