# Generated by Django 2.2.4 on 2019-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedforms', '0002_auto_20190826_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='stat',
            field=models.BooleanField(default=True, verbose_name='Passed'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Home Address'),
        ),
    ]
