# Generated by Django 2.2.4 on 2019-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedforms', '0003_auto_20190827_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
