# Generated by Django 2.2.4 on 2019-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('foreignkeys', '0002_manytomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='manytomany',
            name='car',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
