# Generated by Django 2.2.4 on 2019-08-30 11:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('foreignkeys', '0005_auto_20190830_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Fromothermodel',
        ),
    ]
