# Generated by Django 2.2.4 on 2019-08-30 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreignkeys', '0007_auto_20190830_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='For_On_Delete',
            new_name='ForOnDelete',
        ),
        migrations.RenameModel(
            old_name='From_other_model',
            new_name='FromOtherModel',
        ),
        migrations.RenameModel(
            old_name='Many_to_many',
            new_name='ManyToMany',
        ),
        migrations.RenameModel(
            old_name='One_to_one',
            new_name='OneToOne',
        ),
    ]
