# Generated by Django 2.2.4 on 2019-08-30 12:18

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('foreignkeys', '0008_auto_20190830_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForOnDelete',
        ),
    ]
