# Generated by Django 2.2.2 on 2019-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
