# Generated by Django 2.2.2 on 2019-07-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0004_testmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
