# Generated by Django 2.2.2 on 2019-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0005_auto_20190722_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
