# Generated by Django 2.2.2 on 2019-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0006_auto_20190722_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
