# Generated by Django 2.2.2 on 2019-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0007_testmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(default='hello', max_length=20),
        ),
    ]
