# Generated by Django 2.2.2 on 2019-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0009_testmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
