# Generated by Django 2.2.2 on 2019-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0010_auto_20190723_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
