# Generated by Django 2.2.2 on 2019-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0011_auto_20190723_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(default='hello', max_length=20, verbose_name='Post model'),
        ),
    ]
