# Generated by Django 2.2.2 on 2019-07-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0012_auto_20190723_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
