# Generated by Django 2.2.2 on 2019-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0013_auto_20190723_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(default='hello', max_length=20),
        ),
    ]
