# Generated by Django 2.2.2 on 2019-07-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0015_auto_20190723_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abc',
            new_name='AbcModelGet',
        ),
    ]
