# Generated by Django 2.2.2 on 2019-07-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0016_auto_20190723_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Post'},
        ),
    ]
