# Generated by Django 2.2.2 on 2019-07-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0018_auto_20190723_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='publish',
            field=models.CharField(choices=[('foot', 'Football'), ('cri', 'Cricket'), ('bas', 'Basketball')], default='foot', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(default='hello', max_length=20, unique=True, verbose_name='Post model'),
        ),
    ]
