# Generated by Django 2.2.2 on 2019-08-01 14:51

from django.db import migrations, models
import form1.validators


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0020_auto_20190726_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='author_email',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[form1.validators.validate_email], verbose_name='email'),
        ),
    ]
