# Generated by Django 2.2.2 on 2019-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0021_auto_20190801_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Django Bulitin email'),
        ),
    ]
