# Generated by Django 2.2.2 on 2019-08-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0022_testmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='eshow',
            field=models.CharField(error_messages={'required': 'Value required ', 'unique': ' This field Must not be repeated'}, help_text='Please Try again with other value or enter anything', max_length=30, null=True, verbose_name='For Custom Error show'),
        ),
    ]
