# Generated by Django 2.2.2 on 2019-08-02 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0024_auto_20190801_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='cdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DateField'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='eshow',
            field=models.CharField(error_messages={'required': 'Value required ', 'unique': ' This field Must not be repeated'}, help_text='This field should not be null and must be unique', max_length=30, null=True, unique=True, verbose_name='For Custom Error show'),
        ),
    ]
