# Generated by Django 2.2.2 on 2019-08-04 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0026_auto_20190802_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='tstamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
    ]
