# Generated by Django 2.2.4 on 2019-08-20 06:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0028_auto_20190805_2030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testmodel',
            managers=[
                ('other', django.db.models.manager.Manager()),
            ],
        ),
    ]
